### ISSUE TITLE
sshkit depends on colorize version >= 0.6.0, but colorize 0.7.5 appears to remove String::COLORS

### ISSUE THREAD

**Issue by daines** [capistrano/sshkit#200]
I ran into this error when runnning a fresh install of SSHKit (via installing Capistrano):

```
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sshkit-1.6.0/lib/sshkit/color.rb:4:in `<module:Color>': uninitialized constant String::COLORS (NameError)
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sshkit-1.6.0/lib/sshkit/color.rb:3:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sshkit-1.6.0/lib/sshkit/all.rb:6:in `require_relative'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sshkit-1.6.0/lib/sshkit/all.rb:6:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sshkit-1.6.0/lib/sshkit.rb:35:in `require_relative'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sshkit-1.6.0/lib/sshkit.rb:35:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/capistrano-3.3.5/lib/capistrano/all.rb:2:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/capistrano-3.3.5/bin/cap:2:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.1.5/bin/cap:23:in `load'
    from /usr/local/var/rbenv/versions/2.1.5/bin/cap:23:in `<main>'
```

It looks like SSHKit assumes that colorize defines the String::COLORS constant, but this appears to have been removed in colorize 0.7.5.

**Comment by danmayer** [comment]
for now forcing colorize to 0.6.0 solved the issue for me
