### ISSUE TITLE
SSHKit::Runner::ExecuteError: Exception while executing as deploy@target.ch: no implicit conversion of Hash into String

### ISSUE THREAD

**Issue by raskhadafi** [capistrano/sshkit#203]
After `bundle update` which updated all outdated gems. See the list.

* capistrano (3.3.4 -> 3.3.5)
* colorize (0.7.4 -> 0.7.5)
* sshkit (1.5.1 -> 1.6.1)

Following error occured.

```bash
** Invoke application:staging (first_time)
** Invoke capwodi:ensure_latest_version (first_time)
** Execute capwodi:ensure_latest_version
** Execute application:staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke check:default (first_time)
** Invoke check:app_user (first_time)
** Execute check:app_user
** Execute check:default
** Invoke rvm:hook (first_time)
** Execute rvm:hook
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@server.ch: no implicit conversion of Hash into String
/User/home/me/gems/colored-1.2/lib/colored.rb:70:in `colorize'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/color.rb:7:in `black'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/formatters/pretty.rb:67:in `level'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/formatters/pretty.rb:22:in `write_command'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/formatters/pretty.rb:10:in `write'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:134:in `block in _execute'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:62:in `test'
lib/tasks/cap/rvm.cap:19:in `block (3 levels) in <top (required)>'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
TypeError: no implicit conversion of Hash into String
/User/home/me/gems/colored-1.2/lib/colored.rb:70:in `colorize'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/color.rb:7:in `black'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/formatters/pretty.rb:67:in `level'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/formatters/pretty.rb:22:in `write_command'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/formatters/pretty.rb:10:in `write'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:134:in `block in _execute'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:62:in `test'
lib/tasks/cap/rvm.cap:19:in `block (3 levels) in <top (required)>'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/User/home/me/gems/sshkit-1.6.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => rvm:hook
```

I could solve the problem by fixing the gem version number of colorize to 0.7.4.
May I suggest to do it so in the gemspec of sshkit?

Anyway thanks for this great tool! :+1:

**Comment by leehambley** [comment]
We solved this also by locking the version dep for Capistrano, but we should address it here too, ther was a PR that solved the underlying issue afaik, I thought I merged it.

**Comment by dginther** [comment]
Having this issue as well, and it's preventing SSHkit from doing the rest of the deploy as well,
    cap staging deploy
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@10.0.1.246: undefined method `colorize' for :ubuntu:Symbol

NoMethodError: undefined method `colorize' for :ubuntu:Symbol

Tasks: TOP => deploy:check => safe_deploy_to:ensure => safe_deploy_to:create
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ubuntu@10.0.1.246: undefined method `colorize' for :ubuntu:Symbol

**Comment by shaneog** [comment]
Same issue for me with the following gem versions:

- capistrano: 3.3.5
- colorize: 0.7.5
- sshkit: 1.6.1

Locking `colorize` to `0.7.4` fixed it for me

**Comment by sporkd** [comment]
Yup. Same here.

**Comment by davidcpell** [comment]
same issue here

**Comment by cristiansorinel** [comment]
I had the same issue with:
1. capistrano-3.4.0
2. sshkit-1.7.1
3. colorize-0.7.5

A quick workaround for me was to use strings instead of symbols.

**Comment by leehambley** [comment]
Colorize dependency was removed in db7de6daae7211a3fd39d53833e2466d2c614d28
