### ISSUE TITLE
Cannot create tmp dir when using rootsh shell on the remote server user account

### ISSUE THREAD

**Issue by fgbreel** [capistrano/sshkit#230]
Hi guys, I'm not sure if I here is the right place to open this issue or in capistrano repository, but I'm having a problem to deploy to a server who the default shell is rootsh.

Changing to bash shell solves the problem, but I become unable to audit my server.

Below is the error message with the first deploy attempt:

```
❯ cap staging deploy:check --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
INFO [88907a94] Running /usr/bin/env mkdir -p /tmp/foo/ as fgbreel@10.10.10.10
DEBUG [88907a94] Command: /usr/bin/env mkdir -p /tmp/foo/
DEBUG [88907a94] 	/tmp/foo/: No such file or directory
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as fgbreel@10.10.10.10: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: /tmp/foo/: No such file or directory
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: /tmp/foo/: No such file or directory
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/tasks/git.rake:17:in `block (3 levels) in <top (required)>'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => git:check => git:wrapper
```

And this is the error after create directory manually (paying attention to the user and umask, etc) :

```
❯ cap staging deploy:check --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
INFO [58a23b25] Running /usr/bin/env mkdir -p /tmp/foo/ as fgbreel@10.10.10.10
DEBUG [58a23b25] Command: /usr/bin/env mkdir -p /tmp/foo/
DEBUG [58a23b25] 	cp:
DEBUG [58a23b25] 	cannot stat `mkdir'
DEBUG [58a23b25] 	: No such file or directory
DEBUG [58a23b25]
DEBUG [58a23b25] 	cp:
DEBUG [58a23b25] 	cannot stat `-p'
DEBUG [58a23b25] 	: No such file or directory
DEBUG [58a23b25]
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as fgbreel@10.10.10.10: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: cp: cannot stat `mkdir': No such file or directory
cp: cannot stat `-p': No such file or directory
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: cp: cannot stat `mkdir': No such file or directory
cp: cannot stat `-p': No such file or directory
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/tasks/git.rake:17:in `block (3 levels) in <top (required)>'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => git:check => git:wrapper
```

These are the versions who I'm using:
```
❯ gem list --local | grep -i "ssh\|capis"
capistrano (3.4.0, 3.1.0) # same problem with 3.1.0, 3.3.5 and 3.4.0
sshkit (1.7.1, 1.3.0) # boot versions, same problem, but with the 1.3.0  the error is less helpful.

❯ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]

❯ cap -v
Capistrano Version: 3.4.0 (Rake Version: 10.4.2)
```

Regards
Gabriel Francisco

**Comment by leehambley** [comment]
I'm without a real net conn at home, so responding from my phone. I'm not
familiar with rootsh, however sounds like the command map has default which
expects "/usr/bin/env >thing<" is the problem... You can replace that hash
default (ruby Hash takes a block which is used to "lookup" missing keys,
that's where /use/bin/env is coming from in this instance).. Please check
all the SSHKIT docs and readme for how the command map works there, and see
if you can come up with some sane-for-you defaults that work with rootsh.

**Comment by fgbreel** [comment]
Hi @leehambley , following your advice, I replaced the command_map using this block:

```ruby
SSHKit.config.command_map = Hash.new do |hash, command|
   hash[command] = "#{command}"
end 

```
But I received this other error:

```sh
❯ cap staging deploy:check --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
INFO [0e334e6a] Running mkdir -p /tmp/foo/ as fgbreel@10.10.10.10
DEBUG [0e334e6a] Command: mkdir -p /tmp/foo/
DEBUG [0e334e6a] 	usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
DEBUG [0e334e6a] 	           [-l limit] [-o ssh_option] [-P port] [-S program]
DEBUG [0e334e6a] 	           [[user@]host1:]file1 ... [[user@]host2:]file2
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as fgbreel@10.10.10.10: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/tasks/git.rake:17:in `block (3 levels) in <top (required)>'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => git:check => git:wrapper
```

Then I echoed the $PATH and seems like a rootsh bug (?): 

```sh
❯ cap staging deploy:check --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
INFO [b34da027] Running echo $PATH && mkdir -p /tmp/foo/ as gabrielfrancisco@10.10.10.10
DEBUG [b34da027] Command: echo $PATH && mkdir -p /tmp/foo/
DEBUG [b34da027] 	rootsh: bad characters in arguments
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as gabrielfrancisco@10.10.10.10: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: rootsh: bad characters in arguments
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: rootsh: bad characters in arguments
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/tasks/git.rake:17:in `block (3 levels) in <top (required)>'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/fgbreel/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => git:check => git:wrapper
```

I'm digging into the rootsh sources to verify...

**Comment by leehambley** [comment]
Your rootfs (whatever that is) appears to be broken, and not to have a
`mkdir` command, it's printing as you can see the `scp` usage info. Can't
you use a normal shell on the remote server, what are you trying to achieve
by using this rootfs?

**Comment by leehambley** [comment]
Please excuse all corrections of rootsh to rootfs :-\ damned phone.

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by fgbreel** [comment]
Seems like a bug in [rootsh](http://fossies.org/linux/rootsh/src/rootsh.c)

**Comment by leehambley** [comment]
Thanks for reporting it anyway :) Good luck!
