### ISSUE TITLE
NoMethodError: undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by leemour** [capistrano/sshkit#254]
When I run `bundle exec cap production deploy` I get:
```
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
NoMethodError: undefined method `match' for nil:NilClass
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/host.rb:103:in `suitable?'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/host.rb:38:in `block in initialize'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/host.rb:37:in `select'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/host.rb:37:in `initialize'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/configuration/server.rb:9:in `new'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/configuration/server.rb:9:in `[]'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/configuration/servers.rb:11:in `add_host'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/configuration.rb:59:in `server'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/dsl/env.rb:43:in `server'
config/deploy/production.rb:11:in `<top (required)>'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/setup.rb:15:in `load'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/setup.rb:15:in `block (2 levels) in <top (required)>'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/home/leemour/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/home/leemour/.rbenv/versions/2.1.6/bin/cap:23:in `load'
/home/leemour/.rbenv/versions/2.1.6/bin/cap:23:in `<main>'
Tasks: TOP => production
```
I'm using capistrano (3.4.0)  capistrano-rails (1.1.3) sshkit (1.7.1)
Capistrano used to work on this project but not anymore.

**Comment by mtczerwinski** [comment]
Any progress on it? Have you solved this problem?

**Comment by leemour** [comment]
Solved it. There was an error in my settings can't remembet what it was though.

**Comment by FanaHOVA** [comment]
Had the same issue, check your `deploy.rb` file and make sure the IP of the server is stated correctly. If you use ENV variables to store it using stuff like dotenv, make sure to source the .env file (or equivalent).
