### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by oozzal** [capistrano/sshkit#325]
I get the following error on this line:
https://github.com/capistrano/rbenv/blob/master/lib/capistrano/tasks/rbenv.rake#L10

Basically, the error comes while executing any command. Any issue with my JRuby installation?

It seems like an issue with `jruby-openssl` and `bouncycastle`. [#issue53](https://github.com/jruby/jruby-openssl/issues/53)

But anyways, does `sshkit` support `jruby` yet? I'm using `jruby-9.0.5.0`.

```
Exception in thread "Ruby-0-Thread-10: /Users/uzzaldevkota/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:11" java.lang.ClassCas
tException: org.bouncycastle.asn1.DERApplicationSpecific cannot be cast to org.bouncycastle.asn1.ASN1Sequence
at org.jruby.ext.openssl.impl.PKey.readRSAPrivateKey(PKey.java:151)
at org.jruby.ext.openssl.impl.PKey.readRSAPrivateKey(PKey.java:145)
at org.jruby.ext.openssl.impl.PKey.readPrivateKey(PKey.java:101)
at org.jruby.ext.openssl.PKey$PKeyModule.read(PKey.java:119)
at org.jruby.ext.openssl.PKey$PKeyModule$INVOKER$s$0$1$read.call(PKey$PKeyModule$INVOKER$s$0$1$read.gen)
at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:729)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:414)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:348)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:140)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:126)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:414)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:348)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:140)
at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:126)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:414)
at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:348)
at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:179)
at org.jruby.runtime.BlockBody.yield(BlockBody.java:96)
at org.jruby.runtime.Block.yield(Block.java:166)
at org.jruby.RubyArray.collect(RubyArray.java:2286)
at org.jruby.RubyArray.map19(RubyArray.java:2300)
at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(RubyArray$INVOKER$i$0$0$map19.gen)
at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:494)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
```

**Comment by leehambley** [comment]
We do not support JRuby https://github.com/capistrano/sshkit/blob/master/.travis.yml#L2-L6 - but if you can fix the tests under JRuby we'd be glad to start.

**Comment by mattbrictson** [comment]
I think your problem might be due to https://github.com/jruby/jruby-openssl/issues/36:

> JRuby-OpenSSL does not decode DERApplicationSpecific objects

SSHKit doesn't officially support JRuby, and the automated tests fail under JRuby, but there is no reason it shouldn't work in the general case. I just tested doing a `cap deploy` using JRuby 9.0.4.0 and it worked fine for me.

I don't know enough about SSL to guess how you might work around the `DERApplicationSpecific` limitation, or why your SSH server exhibits the problem but mine does not.

**Comment by oozzal** [comment]
Thanks @mattbrictson. Will switch from capistrano to [mina](https://github.com/mina-deploy/mina/blob/master/.travis.yml#L8)

**Comment by mattbrictson** [comment]
OK, my understanding is that Mina uses the external `ssh` binary, and therefore it won't run into this particular JRuby issue.
