### ISSUE TITLE
Decrypt failed on private key

### ISSUE THREAD

**Issue by matiaskorhonen** [capistrano/sshkit#441]
I get this when trying to deploy using capistrano:

```
SSHKit::Runner::ExecuteError: Exception while executing as deploy@myhost.example.com: Decrypt failed on private key
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
ArgumentError: Decrypt failed on private key
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/ed25519.rb:114:in `initialize'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/ed25519.rb:146:in `new'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/ed25519.rb:146:in `read'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/key_factory.rb:114:in `block in classify_key'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/key_factory.rb:61:in `load_data_private_key'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/key_factory.rb:44:in `load_private_key'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:119:in `each'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `each'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh/authentication/session.rb:71:in `authenticate'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/net-ssh-5.0.2/lib/net/ssh.rb:246:in `start'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:59:in `call'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:59:in `with'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/netssh.rb:176:in `with_ssh'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/netssh.rb:129:in `execute_command'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/abstract.rb:145:in `block in create_command_and_execute'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/abstract.rb:145:in `tap'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/abstract.rb:145:in `create_command_and_execute'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/abstract.rb:78:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/capistrano-3.11.0/lib/capistrano/scm/tasks/git.rake:8:in `block (3 levels) in eval_rakefile'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/matt/.rvm/gems/ruby-2.3.3/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:check => git:check => git:wrapper
```

Before this, I got the error messages about adding the `ed25519` and `bcrypt_pbkdf` gems but I don't even use ed25519 keys for this host.

* Ruby version: 2.3.3
* sshkit 1.17.0

**Comment by leehambley** [comment]
@matiaskorhonen can you rule out SSHKit here, and try a minimal example from the Net::SSH docs to see if your key is loadable?

Looking at the stack trace there's nothing in SSHKit itself that cares about your key, three lines in and you're already in the key parsing of one our dependencies.

Thanks,

**Comment by matiaskorhonen** [comment]
I think you're right that this is a net-ssh bug. It also appears to be non-deterministic so I'm having trouble reproducing it now.

**Comment by rodrigo-toledo-dev** [comment]
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@18.231.20.50: Decrypt failed on private key

I don't know what it's wrong in config.

**Comment by jraedisch** [comment]
Just in case others find this: I could fix this problem by following these steps (macOS only):

https://productiveness.josefglatz.at/fix-ssh-problems-in-macos-sierra-fd606499f361
