### ISSUE TITLE
undefined method `[]' for nil:NilClas

### ISSUE THREAD

**Issue by jnaklaas** [capistrano/sshkit#475]
Got an error trying to run capistrano deploy. I'm having this in all my web projects since a clean install, so I guess it might have to do with an issue with later capistrano or sshkit versions.

Before I also didn't need to use the ed25519 and bcrypt_pbkdf gems for capistrano to work.

```
Enter passphrase for ~/.ssh/id_rsa:
#<Thread:0x00007fb6ed16fc00@~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.19.1/lib/sshkit/runners/parallel.rb:10
run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from ~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.19.1/lib/sshkit/runners/parallel.rb:11:slight_smile:  `block (2 levels) in execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.19.1/lib/sshkit/runners/parallel.rb:15:
in `rescue in block (2 levels) in execute': 
Exception while executing as user@ssh.domain.tld: undefined method `[]' for nil:NilClass (SSHKit::Runner::ExecuteError)

(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@ssh.domain.tld: undefined method `[]' for nil:NilClass

Caused by:
NoMethodError: undefined method `[]' for nil:NilClass
```

I have no idea how to interpret or fix this error.

**Comment by mattbrictson** [comment]
Thanks for the report! To be honest this error message is pretty ambiguous and I am not sure how to interpret it either. We will need your help to figure this out.

1. What command are you running that triggers this error? `cap production deploy` or something else?
2. When does the error occur? Immediately or do some capistrano tasks work and the failure happens further along?
3. Can we see the logging output the leads up to this error?
4. Have you tried re-running the command with `--trace` for more troubleshooting information?
5. Could you post the output of `cap production doctor`?
6. Have you tried installing an older version of capistrano or sshkit (i.e. the ones that were working for you previously)?
7. What other troubleshooting steps have you tried?

**Comment by jnaklaas** [comment]
1. `cap production deploy:check`
2. Not immediately:
  `00:00 git:wrapper`
      `01 mkdir -p /tmp`
  `Enter passphrase for ~/.ssh/id_rsa:`
  After entering ssh pass the error is thrown.
3. See (2) and the output from the OP.
4. Yes. Output with `--trace`
```sh
$ cap production deploy:check --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy:check (first_time)
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
00:00 git:wrapper
      01 mkdir -p /tmp
Enter passphrase for ~/.ssh/id_rsa:
#<Thread:0x00007fa4feaaaf50@~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:10 run> terminated with excep
tion (report_on_exception is true):
Traceback (most recent call last):
        1: from ~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception
while executing as user@ssh.domain.tld: undefined method `[]' for nil:NilClass (SSHKit::Runner::ExecuteError)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@ssh.domain.tld: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

Caused by:
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519.rb:79:in `read'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:127:in `read'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:61:in `load_data_private_key'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/connection_pool.rb:63:in `call'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/connection_pool.rb:63:in `with'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:177:in `with_ssh'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:130:in `execute_command'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `tap'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:80:in `execute'
~/.rvm/gems/ruby-2.5.6/gems/capistrano-3.11.1/lib/capistrano/scm/tasks/git.rake:8:in `block (3 levels) in eval_rakefile'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `run'
~/.rvm/gems/ruby-2.5.6/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:check => git:check => git:wrapper
```
5. `cap production doctor` output
```
$ cap production doctor

Environment

    Ruby     ruby 2.5.6p201 (2019-08-28 revision 67796) [x86_64-darwin18]
    Rubygems 3.0.6
    Bundler  1.17.3
    Command  ~/.rvm/gems/ruby-2.5.6/bin/cap production doctor

Gems

    capistrano          3.11.1
    airbrussh           1.3.4
    rake                12.3.3
    sshkit              1.20.0
    net-ssh             5.2.0
    capistrano-composer 0.0.6
    capistrano-npm      1.0.3
    capistrano-wpcli    0.1.4

Variables

    :application                    "domainname"
    :branch                         :master
    :composer_download_url          "https://getcomposer.org/installer"
    :composer_dump_autoload_flags   "--optimize"
    :composer_install_flags         "--no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader"
    :composer_roles                 :all
    :composer_working_dir           nil
    :copy_exclude                   [".git", ".DS_Store", ".env.example", "asset-files"]
    :current_time                   "201909161917"
    :default_env                    {:wp_env=>:production}
    :deploy_to                      "~/www"
    :deploy_via                     :copy

    :format                         :airbrussh
    :git_environmental_variables    {:git_askpass=>"/bin/echo", :git_ssh=>"/tmp/git-ssh-domainname-production.sh"}
    :git_shallow_clone              false
    :git_wrapper_path               "/tmp/git-ssh-domainname-production.sh"
    :keep_releases                  3
    :linked_dirs                    ["www/app/uploads"]
    :linked_files                   [".env"]
    :local_app_path                 #<Pathname:~/projects/tfb-domainname>
    :local_dist_path                #<Pathname:~/projects/tfb-domainname/www/app/themes/domainname/dist>
    :local_theme_path               #<Pathname:~/projects/tfb-domainname/www/app/themes/domainname>
    :local_tmp_dir                  "/tmp"
    :local_user                     "user"
    :log_level                      :info
    :pty                            false
    :repo_url                       "git@bitbucket.org:gituser/domainname.git"
    :scm_verbose                    "true"
    :server                         "ssh.domain.tld"
    :ssh_options                    {:keys=>["~/.ssh/id_rsa"], :forward_agent=>true}
    :stage                          :production
    :theme_dir                      "domainname"
    :tmp_dir                        "/tmp"
    :user                           "user"
    :webroot                        "www"
    :wp_roles                       :all
    :wpcli_args                     nil
    :wpcli_backup_db                false
    :wpcli_local_db_backup_dir      "config/backup"
    :wpcli_local_db_backup_filename "db_production_201909161917.sql.gz"
    :wpcli_local_db_file            "/tmp/wpcli_database.sql.gz"
    :wpcli_local_uploads_dir        "web/app/uploads/"
    :wpcli_local_url                "http://example.dev"
    :wpcli_remote_db_file           "/tmp/wpcli_database.sql.gz"
    :wpcli_remote_uploads_dir       "~/www/shared/web/app/uploads/"
    :wpcli_remote_url               "http://example.com"
    :wpcli_rsync_options            "-avz --rsh=ssh --progress"

    :copy_exclude is not a recognized Capistrano setting (~/.rvm/rubies/ruby-2.5.6/lib/ruby/2.5.0/delegate.rb:83)
    :deploy_via is not a recognized Capistrano setting (~/.rvm/rubies/ruby-2.5.6/lib/ruby/2.5.0/delegate.rb:83)
    :local_dist_path is not a recognized Capistrano setting (~/.rvm/rubies/ruby-2.5.6/lib/ruby/2.5.0/delegate.rb:83)
    :scm_verbose is not a recognized Capistrano setting (~/.rvm/rubies/ruby-2.5.6/lib/ruby/2.5.0/delegate.rb:83)

Servers (1)

    user@ssh.domain.tld [:web, :app, :db]
```
6. Yes, I've tried using older versions for ruby, capistrano and other gems, but so far without success.
7. None worth mentioning. Except perhaps for doing another clean install to make sure I didn't mess anyting up during installation. Fwiw, here's my bash install script I run after a sweep:
```sh
# command line tools
xcode-select --install

# homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 

# bash
brew install bash && sudo sh -c 'echo "/usr/local/bin/bash" >> /etc/shells' && chsh -s /usr/local/bin/bash

# localhost dev tools
brew install php
brew install mysql && brew services start mysql
brew install composer
composer global require laravel/valet && valet install && valet start
brew install gettext && echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
brew install coreutils
brew install inetutils

# node
brew install nvm && mkdir ~/.nvm
echo 'export NVM_DIR=~/.nvm' >> ~/.bash_profile
echo 'source $(brew --prefix nvm)/nvm.sh' >> ~/.bash_profile
nvm install --lts
brew install yarn

# ruby
brew install gnupg # install gpg
sudo brew services start unbound
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable --ruby # install ruby version manager
source ~/.rvm/scripts/rvm
```
I copied my web projects in my home directory, identical set-up as where all worked fine last week.
To continue a web project, I `cd` to project directory, and run `bundle install`.

The .gemfiles mostly look like this
```sh
source 'https://rubygems.org'
gem 'capistrano'
gem 'capistrano-composer'
gem 'capistrano-npm'
gem 'capistrano-wpcli'
```

The .capfile:
```sh
require 'capistrano/setup'
require 'capistrano/deploy'
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
require 'capistrano/composer'
require 'capistrano/wpcli'
```

**Comment by mattbrictson** [comment]
Thanks for the additional details. This is a huge help!

I see in the back trace that the error is happening inside the net-ssh gem:

```
Caused by:
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519.rb:79:in `read'
```

For context: sshkit relies on net-ssh for implementing the ssh protocol. Part of what net-ssh does is load and interpret the private keys needed for ssh authentication. It looks like net-ssh is crashing during this step.

Another sshkit user ran into a similar problem before in https://github.com/capistrano/sshkit/issues/442 . This was ultimately determined to be a bug in net-ssh and was fixed there.

My suggestion would be to open a bug report in the [net-ssh repo](https://github.com/net-ssh/net-ssh/issues). In your bug report include the back trace as it will help the net-ssh maintainers understand where the crash occurs:

```
NoMethodError: undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519.rb:79:in `read'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:127:in `read'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:61:in `load_data_private_key'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
~/.rvm/gems/ruby-2.5.6/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
```

Also include the versions of the net-ssh, ed25519, and bcrypt_pbkdf gems that you are using.

I will leave this sshkit ticket open in the meantime just in case they determine it is not an net-ssh issue.

**Comment by jnaklaas** [comment]
Will do, thanks!

**Comment by jnaklaas** [comment]
I suspect there was something wrong with my ssh public/private RSA key pair, which resulted in the above error.

After regenerating a key pair and copying the public key to the server, all worked fine again. Thanks for pointing me in the right direction!
