### ISSUE TITLE
Upgrade to mocha 1.10+

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#479]
There are breaking changes in mocha 1.10 that cause some SSHKit tests to fail. For now we are pinning at 1.9.x as a workaround, but we need to upgrade eventually.

```
  test_can_write_to_output_which_just_supports_append             FAIL (0.00s)
        unexpected invocation: #<Mock:<<>.<<("  INFO [aaaaaa] Running /usr/bin/env a_cmd some args as user@localhost\n")
        satisfied expectations:
        - allowed any number of times, invoked once: #<AnyInstance:SSHKit::Command>.uuid(any_parameters)
        - allowed any number of times, invoked never: #<SSHKit::Command:0x106a283c8>.runtime(any_parameters)
        /Users/mbrictson/Code/capistrano/sshkit/lib/sshkit/formatters/pretty.rb:53:in `write_message'
        /Users/mbrictson/Code/capistrano/sshkit/lib/sshkit/formatters/pretty.rb:21:in `log_command_start'
        /Users/mbrictson/Code/capistrano/sshkit/test/unit/formatters/test_pretty.rb:128:in `simulate_command_lifecycle'
        /Users/mbrictson/Code/capistrano/sshkit/test/unit/formatters/test_pretty.rb:120:in `test_can_write_to_output_which_just_supports_append'
```

**Comment by mattbrictson** [comment]
Fixed via #480
